apiVersion: apps/v1
kind: Deployment
metadata:
  name: collage-erp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collage-erp
  template:
    metadata:
      labels:
        app: collage-erp
    spec:
      containers:
      - name: collage-erp
        image: mohamedahsan00/collage-erp:latest
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: DB_PATH
          value: "/usr/src/app/data/collage.db"
        volumeMounts:
        - name: db-storage
          mountPath: /usr/src/app/data
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: collage-erp-pvc
