apiVersion: v1
kind: Service
metadata:
  name: collage-erp-service
spec:
  type: NodePort
  selector:
    app: collage-erp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007
